Fix name of var

diff --git a/FVEgenPage b/FVEgenPage
--- a/FVEgenPage
+++ b/FVEgenPage
@@ -9,7 +9,7 @@ elif [ -e /etc/FVErc ]; then
 	FVErc="/etc/FVErc"
 	source "$FVEBINDIR"/FVEcomFncs
 else
-	FVErcMSG="ERROR"
+	FVErc="ERROR"
 fi
 
 
@@ -263,7 +263,7 @@ while [ $# -gt 0 ]; do
 			;;
 		--update) UPDATE=Y; shift;;
 		--FVErc)
-			if [ $# -lt 2 ]; then 
+			if [ $# -lt 2 ]; then
 				errorPrint "Not enough params passed for --FVErc"
 				exit 2
 			fi
@@ -280,7 +280,7 @@ while [ $# -gt 0 ]; do
 	esac
 done
 
-if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVEgenPage: FVErc not found!"; exit 99; fi
 debugPrint "Script: FVEgenPage"
 debugPrint "Using FVErc from ${FVErc}"
 
