Add --FVErc opt

diff --git a/FVEgenPage b/FVEgenPage
--- a/FVEgenPage
+++ b/FVEgenPage
@@ -2,13 +2,16 @@
 
 if [ -e ~/.FVErc ]; then 
 	source ~/.FVErc
+	FVErc="HOME"
+	source "$FVEBINDIR"/FVEcomFncs
 elif [ -e /etc/FVErc ]; then
 	source /etc/FVErc
+	FVErc="/etc/FVErc"
+	source "$FVEBINDIR"/FVEcomFncs
 else
-	echo "FVErc not found!"
-	exit 99
+	FVErcMSG="ERROR"
 fi
-source "$FVEBINDIR"/FVEcomFncs
+
 
 function printHelp() {
 	echo "
@@ -141,7 +144,7 @@ echo '  </tr>' >> "$HTMLOPTFILE"
 echo '</table>' >> "$HTMLOPTFILE"
 
 #Run to update statusses, since the page is generated from scratch. Usually only --update is run.
-FVEoptRunV2 -f
+FVEoptRunV2 -f --FVErc $FVErc
 
 }
 
@@ -259,9 +262,28 @@ while [ $# -gt 0 ]; do
 			shift 3
 			;;
 		--update) UPDATE=Y; shift;;
+		--FVErc)
+			if [ $# -lt 2 ]; then 
+				errorPrint "Not enough params passed for --FVErc"
+				exit 2
+			fi
+			if [ -e "$2" ]; then
+				source "$2"
+				FVErc="$2"
+				source "$FVEBINDIR"/FVEcomFncs
+			else
+				errorPrint "FVErc file was not found"
+			fi
+			shift 2;
+			;;
 		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
 	esac
 done
+
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
+debugPrint "Script: FVEgenPage"
+debugPrint "Using FVErc from ${FVErc}"
+
 
 [ "$DIRECTTEMP" = "ON" ] && TEMPERATURE="$(tail -1 $TEMPERATUREFILE | awk '{print $2}')"
 
diff --git a/FVEhistPage b/FVEhistPage
--- a/FVEhistPage
+++ b/FVEhistPage
@@ -2,14 +2,16 @@
 
 if [ -e ~/.FVErc ]; then 
 	source ~/.FVErc
+	FVErc="HOME"
+	source "$FVEBINDIR"/FVEcomFncs
 elif [ -e /etc/FVErc ]; then
 	source /etc/FVErc
+	FVErc="/etc/FVErc"
+	source "$FVEBINDIR"/FVEcomFncs
 else
-	echo "FVErc not found!"
-	exit 99
+	FVErcMSG="ERROR"
 fi
 
-source "$FVEBINDIR"/FVEcomFncs
 
 TRIMMED=${FVEHTMLPOWERNAME%.html}
 FVEPOWERNAMEHIST=$TRIMMED.$TIMEDATE_YYYYMMDD.html
@@ -170,8 +172,25 @@ while [ $# -gt 0 ]; do
 	-d|--debug) VERB=Y;  DEBUG=Y ; shift;;
 	-m|--month) MAKEMTH=Y ; shift;;
 	-y|--year) MAKEYEAR=Y ; shift;;
+	--FVErc)
+	    if [ $# -lt 2 ]; then 
+		errorPrint "Not enough params passed for --FVErc"
+	    	exit 2
+	    fi
+	    if [ -e "$2" ]; then
+		source "$2"
+		FVErc="$2"
+		source "$FVEBINDIR"/FVEcomFncs
+	    else
+		errorPrint "FVErc file was not found"
+	    fi
+	    shift 2;
+	    ;;
 	*)  errorPrint "$0: error - unrecognized option $1" 1>&2; exit 1;;
     esac
 done
 
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
+debugPrint "Script: FVEhistPage"
+debugPrint "Using FVErc from ${FVErc}"
 mainLoop
diff --git a/FVEonOff b/FVEonOff
--- a/FVEonOff
+++ b/FVEonOff
@@ -2,14 +2,15 @@
 
 if [ -e ~/.FVErc ]; then 
 	source ~/.FVErc
+	FVErc="HOME"
+	source "$FVEBINDIR"/FVEcomFncs
 elif [ -e /etc/FVErc ]; then
 	source /etc/FVErc
+	FVErc="/etc/FVErc"
+	source "$FVEBINDIR"/FVEcomFncs
 else
-	echo "FVErc not found!"
-	exit 99
+	FVErcMSG="ERROR"
 fi
-
-source "$FVEBINDIR"/FVEcomFncs
 
 function printHelp() {
 	echo -e "\nusage: `basename $0` [OPTIONS]
@@ -131,7 +132,7 @@ function opt() {
 		realStatus $COMPONENT $EXPECTEDSTATUS
 		local STATUS=$? 
 		if [ $STATUS = 0 -o "$FORCE" = "Y" ] ; then
-			FVEgenPage --update --device $COMPONENT $EXPECTEDSTATUS
+			FVEgenPage --FVErc $FVErc --update --device $COMPONENT $EXPECTEDSTATUS
 		fi
 	else
 		errorPrint "Unknown parametr for function opt(): $@"
@@ -197,9 +198,28 @@ while [ $# -gt 0 ]; do
 			;;
 		--init) initFVEonOff; exit 0;;
 		--destroy) uninitStatuses ;exit 0;;
+		--FVErc)
+			if [ $# -lt 2 ]; then 
+				errorPrint "Not enough params passed for --FVErc"
+				exit 2
+			fi
+			if [ -e "$2" ]; then
+				source "$2"
+				FVErc="$2"
+				source "$FVEBINDIR"/FVEcomFncs
+			else
+				errorPrint "FVErc file was not found"
+			fi
+			shift 2;
+			;;
 		*)  errorPrint "$0: error - unrecognized option $1" 1>&2; exit 1;;
 	esac
 done
+
+
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
+debugPrint "SCRIPT: FVEonOff"
+debugPrint "Using FVErc from ${FVErc}"
 
 if [ "$ALWAYSFORCE" = 'Y' ]; then
     FORCE='Y'
diff --git a/FVEoptRunV2 b/FVEoptRunV2
--- a/FVEoptRunV2
+++ b/FVEoptRunV2
@@ -2,25 +2,15 @@
 
 if [ -e ~/.FVErc ]; then 
 	source ~/.FVErc
+	FVErc="HOME"
+	source "$FVEBINDIR"/FVEcomFncs
 elif [ -e /etc/FVErc ]; then
 	source /etc/FVErc
+	FVErc="/etc/FVErc"
+	source "$FVEBINDIR"/FVEcomFncs
 else
-	echo "FVErc not found!"
-	exit 99
+	FVErcMSG="ERROR"
 fi
-
-source "$FVEBINDIR"/FVEcomFncs
-
-OPTCFGFILE=$OPTCFGFILE
-if [ -e "$CFGDIR"/FVEoptRun.low.cfg ]; then
-	verbPrint "WARNING: found obsoleted configuration file."
-	verbPrint "Please move all configuratoin from"
-	verbPrint "$CFGDIR/FVEoptRun.low.cfg to ~/.FVErc"
-	verbPrint "and remove file $CFGDIR/FVEoptRun.low.cfg"
-	OPTCFGLOWFILE="$CFGDIR"/FVEoptRun.low.cfg
-	source $OPTCFGLOWFILE
-fi
-
 
 function updateEnergy() {
 	ENERGYBUCKET=$(expr $ENERGYBUCKET - $1)
@@ -371,7 +361,7 @@ function decideOnOff() {
 			elif [ $LOCALCONSUMPTION -le $ENERGYBUCKET ] && [ $ENERGYBUCKET -le $STARTLOCALCONSUMPTION ] ; then
 				verbPrint "Device $LOCALDEVICE (ID:$LOCALDEVICEID) CONS:  ${LOCALCONSUMPTION} < $ENERGYBUCKET < $STARTLOCALCONSUMPTION -- nochange" 
 				local STATUS
-				STATUS=$(FVEonOff $VERBPARM $DEBUGPARAM --getstatus $LOCALDEVICE )
+				STATUS=$(FVEonOff $VERBPARM $DEBUGPARAM --getstatus $LOCALDEVICE --FVErc $FVErc)
 				if [ $? != 0 ]; then
 					errorPrint "$LOCALDEVICE (ID:$LOCALDEVICEID) was not recognized in TelDus configuration"
 					continue
@@ -440,7 +430,7 @@ function enableDisableDevices() {
 	local VOID
 	while read DEVICENUM VOID; do
 		verbPrint "Device ${STARTSTOPDEVICENAMES["$DEVICENUM"]} (ID=$DEVICENUM) is being turned ${STARTSTOPDEVICES["$DEVICENUM"]}"
-		FVEonOff $DEBUGPARAM $VERBPARM --setstatus "${STARTSTOPDEVICENAMES["$DEVICENUM"]}" "${STARTSTOPDEVICES["$DEVICENUM"]}"
+		FVEonOff $DEBUGPARAM $VERBPARM  --FVErc $FVErc --setstatus "${STARTSTOPDEVICENAMES["$DEVICENUM"]}" "${STARTSTOPDEVICES["$DEVICENUM"]}"
 		#sleep 2
 	done < <( cat "$OPTCFGFILE" | grep -v \# | sed /^$/d)
 	return 0
@@ -488,16 +478,44 @@ while [ $# -gt 0 ]; do
 		-d|--debug) VERB=Y;  DEBUG=Y ; VERBPARAM='-v'; DEBUGPARAM='--debug'; shift;;
 		-f|--force) FORCE='Y'; shift;;
 		*)  errorPrint "$0: error - unrecognized option $1" 1>&2; exit 1;;
+		--FVErc)
+			if [ $# -lt 2 ]; then
+				errorPrint "Not enough params passed for --FVErc"
+				exit 2
+			fi
+			if [ -e "$2" ]; then
+				source "$2"
+				FVErc="$2"
+				source "$FVEBINDIR"/FVEcomFncs
+			else
+				errorPrint "FVErc file was not found"
+			fi
+			shift 2;
+			;;
 	esac
 done
+
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
+debugPrint "SCRIPT: FVEoptRunV2"
+debugPrint "Using FVErc from ${FVErc}"
+
+OPTCFGFILE=$OPTCFGFILE
+if [ -e "$CFGDIR"/FVEoptRun.low.cfg ]; then
+	verbPrint "WARNING: found obsoleted configuration file."
+	verbPrint "Please move all configuratoin from"
+	verbPrint "$CFGDIR/FVEoptRun.low.cfg to ~/.FVErc"
+	verbPrint "and remove file $CFGDIR/FVEoptRun.low.cfg"
+	OPTCFGLOWFILE="$CFGDIR"/FVEoptRun.low.cfg
+	source $OPTCFGLOWFILE
+fi
 
 checkUptime
 getBucket
 
-FVEonOff --init
+FVEonOff --init   --FVErc $FVErc 
 
 mainLoop
 
-FVEonOff --destroy
+FVEonOff --destroy   --FVErc $FVErc 
 
 exit 0
diff --git a/FVEread b/FVEread
--- a/FVEread
+++ b/FVEread
@@ -1,15 +1,16 @@
 #!/bin/bash
-
 if [ -e ~/.FVErc ]; then 
 	source ~/.FVErc
+	FVErc="HOME"
+	source "$FVEBINDIR"/FVEcomFncs
 elif [ -e /etc/FVErc ]; then
 	source /etc/FVErc
+	FVErc="/etc/FVErc"
+	source "$FVEBINDIR"/FVEcomFncs
 else
-	echo "FVErc not found!"
-	exit 99
+	FVErcMSG="ERROR"
 fi
 
-source "$FVEBINDIR"/FVEcomFncs
 
 function printHelp() {
 	echo -e "usage: `basename $0` [OPTIONS]
@@ -144,13 +145,13 @@ function updateProductionFile() {
 function checkFileExist() {
 	debugPrint "FNC: checkFileExist"
 	if [ ! -e $HTMLFILE ]; then
-		FVEgenPage --defpage
+		FVEgenPage --defpage --FVErc "$FVErc"
 	fi
 	if [ ! -e "$HTMLOPTFILE" ]; then
-		FVEgenPage --optpage
+		FVEgenPage --optpage --FVErc "$FVErc"
 	fi
 	if [ `cat $HTMLOPTFILE | wc -l` -le 1 ]; then
-		FVEgenPage --optpage
+		FVEgenPage --optpage --FVErc "$FVErc"
 	fi
 }
 
@@ -278,14 +279,14 @@ function genFiles() {
 	#usage: genFiles
 		echo $TIMEDATE_YYYYMMDDHHmm $CURRENT $TODAY $AVRG $L1 $L2 $L3 $rawTOTALPRODUCED >> "$HISTORYFILE"
 
-		debugPrint "Running: FVEgenPage  --powerpage --current $CURRENT --L1 $L1 --L2 $L2 --L3 $L3 --today $TODAY --fvestatus $FVESTATUS --avrg $AVRG"
-		FVEgenPage  --powerpage --current $CURRENT --L1 $L1 --L2 $L2 --L3 $L3 --today $TODAY --fvestatus $FVESTATUS --avrg $AVRG
+		debugPrint "Running: FVEgenPage  --powerpage --current $CURRENT --L1 $L1 --L2 $L2 --L3 $L3 --today $TODAY --fvestatus $FVESTATUS --avrg $AVRG"  --FVErc "$FVErc"
+		FVEgenPage  --powerpage --current $CURRENT --L1 $L1 --L2 $L2 --L3 $L3 --today $TODAY --fvestatus $FVESTATUS --avrg $AVRG  --FVErc "$FVErc"
 		
 		updateProductionFile
 		
-		FVEgenGraphs --all
+		FVEgenGraphs --all  --FVErc "$FVErc"
 		if [ "$DIRECTTEMP" = "ON" ]; then
-			FVEgenGraphs --temperature
+			FVEgenGraphs --temperature  --FVErc "$FVErc"
 		fi
 		createAPIfile
 }
@@ -314,7 +315,7 @@ function genHist() {
 	fi
 	if [ $HISTORY ]; then
 		verbPrint "Generating history"
-		FVEhistPage $VERBPARM $DEBUGPARM
+		FVEhistPage $VERBPARM $DEBUGPARM --FVErc "$FVErc"
 	fi
 }
 
@@ -337,7 +338,7 @@ function mainLoop() {
 	else
 		genFiles
 		checkFileExist
-		FVEoptRunV2 $VERBPARM $DEBUGPARM
+		FVEoptRunV2 $VERBPARM $DEBUGPARM   --FVErc $FVErc 
 		#Close API json file
 		echo '}' >> "$FVEAPIFILE"
 		uploadDataFTP
@@ -359,7 +360,7 @@ while [ $# -gt 0 ]; do
 		--history) HISTORY=Y; shift ;;
 		--disable) 
 			disableMe 2>/dev/null
-			FVEoptRunV2 --off
+			FVEoptRunV2 --off --FVErc $FVErc 
 			shift
 			exit 0
 			;;
@@ -389,6 +390,20 @@ while [ $# -gt 0 ]; do
 			errorPrint "Done. Please re-run the FVEread."
 			exit 0
 			;;
+		--FVErc)
+			if [ $# -lt 2 ]; then
+				errorPrint "Not enough params passed for --FVErc"
+				exit 2
+			fi
+			if [ -e "$2" ]; then
+				source "$2"
+				FVErc="$2"
+				source "$FVEBINDIR"/FVEcomFncs
+			else
+				errorPrint "FVErc file was not found"
+			fi
+			shift 2;
+			;;
 		--vacation)
 			if [ $# -lt 3 ]; then 
 				errorPrint "Not enough params passed for --vacation"
@@ -415,5 +430,9 @@ while [ $# -gt 0 ]; do
 		*)  errorPrint "$0: error - unrecognized option $1" 1>&2; exit 1;;
 	esac
 done
+
+if [ "$FVErc" = "ERROR" ]; then errorPrint "FVErc not found!"; exit 99; fi
 debugPrint "SCRIPT: FVEread"
+debugPrint "Using FVErc from ${FVErc}"
+
 mainLoop
