Changed --update --device logic and parametrs handling for FVEgenPage

diff --git a/FVEgenPage b/FVEgenPage
--- a/FVEgenPage
+++ b/FVEgenPage
@@ -40,7 +40,6 @@ function printLoadedParams() {
 	BOILER1=$BOILER1
 	FUKAR1=$FUKAR1
 	KLIMA1=$KLIMA1
-	LSTATUS=$LSTATUS
 	"
 }
 
@@ -96,21 +95,12 @@ cat > "$HTMLOPTFILE" << EOF
     <th>Lacerta</th>
     <th>Boiler 1</th>
     <th>Fukar 1</th>
-    <th>Klimatizace 1</th>
   </tr>
   <tr valign="middle" align="center">
     <td>Designed status:</td>
     <td><img src=lacerta-$LACERTA.png></td>
     <td><img src=boiler1-$BOILER1.png></td>
     <td><img src=fukar1-$FUKAR1.png></td>
-    <td><img src=klima1-$KLIMA1.png></td>
-  </tr>
-    <tr valign="middle" align="center">
-    <td>Real status:</td>
-    <td><img src=lacerta-stat-$LSTATUS.png></td>
-    <td><img src=unknown-status.jpg alt="Unknown"></td>
-    <td><img src=unknown-status.jpg alt="Unknown"></td>
-    <td><img src=unknown-status.jpg alt="Unknown"></td>
   </tr>
 </table>
 EOF
@@ -151,70 +141,43 @@ function checkStatus() {
 }
 
 function updateOptFile() {
-	if [ $LACERTA ]; then
-	checkStatus lacerta $LACERTA
-		if [ $LACERTA = on ]; then
-			sed -i 's/lacerta-off/lacerta-on/g' $HTMLOPTFILE 
-		elif [ $LACERTA = off ]; then
-			sed -i 's/lacerta-on/lacerta-off/g' $HTMLOPTFILE 
+	for NUM in $(seq 0 $(expr $DEVICENUM - 1 )); do
+	checkStatus ${DEVICENAME[$NUM]} ${DEVICESTATUS[$NUM]}
+		if [ ${DEVICESTATUS[$NUM]} = on ]; then
+			sed -i s/${DEVICENAME[$NUM]}-off/${DEVICENAME[$NUM]}-on/g $HTMLOPTFILE 
+		elif [ ${DEVICESTATUS[$NUM]} = off ]; then
+			sed -i s/${DEVICENAME[$NUM]}-on/${DEVICENAME[$NUM]}-off/g $HTMLOPTFILE 
 		fi
-	fi	
-	if [ $BOILER1 ]; then	
-	checkStatus boiler1 $BOILER1
-		if [ $BOILER1 = on ]; then
-			sed -i 's/boiler1-off/boiler1-on/g' $HTMLOPTFILE 
-		elif [ $BOILER1 = off ]; then
-			sed -i 's/boiler1-on/boiler1-off/g' $HTMLOPTFILE 
-		fi
-	fi
-	if [ $FUKAR1 ]; then	
-	checkStatus fukar1 $FUKAR1
-		if [ $FUKAR1 = on ]; then
-			sed -i 's/fukar1-off/fukar1-on/g' $HTMLOPTFILE 
-		elif [ $FUKAR1 = off ]; then
-			sed -i 's/fukar1-on/fukar1-off/g' $HTMLOPTFILE 
-		fi	
-	fi
-	if [ $KLIMA1 ]; then	
-	checkStatus klima1 $KLIMA1
-		if [ $KLIMA1 = on ]; then
-			sed -i 's/klima1-off/klima1-on/g' $HTMLOPTFILE 
-		elif [ $KLIMA1 = off ]; then
-			sed -i 's/klima1-on/klima1-off/g' $HTMLOPTFILE 
-		fi	
-	fi
+	done
 }
 
-if ! options=$(getopt -o fvuodpla:s:c:t:A:B:C:D: -l off,verbose,update,optpage,defpage,powerpage,lstatus,avrg:,fvestatus:,current:,today:,lacerta:,boiler1:,fukar1:,klima1: -- "$@")
-#if ! options=$(getopt -o c: -l current: -- "$@" )
-then
-    # something went wrong, getopt will put out an error message for us
-    exit 1
-fi
-eval set -- $options
-
+DEVICENUM=0
 while [ $# -gt 0 ]; do
 	case $1 in
-		-v|--verbose) VEBROSE="Y";;
-		-d|--defpage) GENDEFPAGE=Y;;
-		-f|--off) LACERTA=off ; BOILER1=off;FUKAR1=off;;
-		-o|--optpage) GENOPTPAGE=Y;;
-		-p|--powerpage) GENPOWERPAGE=Y;;
-		-l|--lstatus) LSTATUS=Y;;
-		-s|--fvestatus) FVESTATUS="$2"; shift;;
-		-c|--current) FVECURRENT="$2"; shift;;
-		-t|--today) FVETODAY="$2"; shift;;
-		-a|--avrg)	FVEAVRG="$2"; shift;;
-		-A|--lacerta) LACERTA="$2"; shift;;
-		-B|--boiler1) BOILER1="$2"; shift;;
-		-C|--fukar1) FUKAR1="$2"; shift;;
-		-D|--klima1) KLIMA1="$2"; shift;;
-		-u|--update) UPDATE=Y;;
-		(--) shift; break;;
-		(-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
-		(*) break;;
+		-v|--verbose) VEBROSE="Y"; shift;;
+		--defpage) GENDEFPAGE=Y; shift;;
+		--off) LACERTA=off ; BOILER1=off;FUKAR1=off; shift;;
+		--optpage) GENOPTPAGE=Y; shift;;
+		--powerpage) GENPOWERPAGE=Y; shift;;
+		--fvestatus) FVESTATUS="$2"; shift 2;;
+		--current) FVECURRENT="$2"; shift 2;;
+		--today) FVETODAY="$2"; shift 2;;
+		--avrg)	FVEAVRG="$2"; shift 2;;
+		--lacerta) LACERTA="$2"; shift 2;;
+		--boiler1) BOILER1="$2"; shift 2;;
+		--fukar1) FUKAR1="$2"; shift 2;;
+		--device) 
+			if [ $# -lt 3 ]; then 
+				echo "Not enough params passed for --device"
+				exit 2
+			fi
+			DEVICENAME[$DEVICENUM]="$2"
+			DEVICESTATUS[$DEVICENUM]="$3"
+			((++DEVICENUM)) 
+			shift 3;;
+		--update) UPDATE=Y; shift;;
+		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
 	esac
-	shift
 done
 
 if [ $# -gt 0 ]; then
@@ -232,6 +195,7 @@ if [ -z $GENDEFPAGE ] && [ -z $GENOPTPAGE ] && [ -z $GENPOWERPAGE ] && [ -z $UPD
 	GENOPTPAGE: $GENOPTPAGE
 	GENPOWERPAGE: $GENPOWERPAGE
 	"
+	exit 1
 fi
 
 if [ $GENDEFPAGE ]; then
@@ -245,10 +209,9 @@ if [ $GENOPTPAGE ]; then
 		LACERTA=off
 		BOILER1=off
 		FUKAR1=off
-		KLIMA1=off
 	fi
 		#checkStatus 
-		updateLacertaStatus
+		#updateLacertaStatus
 		genOptsPage
 	#fi
 fi
