Supports getstatus, code to on/off device has been taken from old code, should I rewrite...?

diff --git a/FVEonOff b/FVEonOff
--- a/FVEonOff
+++ b/FVEonOff
@@ -23,33 +23,103 @@ function checkTDstatus() {
 
 function getTDstatuses() {
 	> "$TMPDIR"/FVE.statuses
-	tdtool -l > "$TMPDIR"/FVE.statuses
+	tdtool -l > "$TMPDIR"/FVE.statuses 
 }
 
-function getStatuses() {
-	checkTDstatus
+function initFVEonOff() {
+	#checkTDstatus
 	getTDstatuses
 }
-
-
 
 function uninitStatuses() {
 	rm -f "$TMPDIR"/FVE.statuses
 	return $?
 }
 
-function getDeviceStatus() {
-	return 0
+function getDeviceNumber() {
+	#usage: getDeviceNumber $COMPONENT
+	local COMPONENT=$1
+	debugPrint "Getting device number for: $COMPONENT"
+	DEVICENUM=$( grep -B1 $COMPONENT /etc/tellstick.conf | head -1 | awk '{print $NF}')
+}
+
+function realStatus(){
+	#usage: getStatus $COMPONENT $STATUS
+	#retval: 0 -- the status was changed
+	#        1 -- OK, but status was not changed
+	#        2 -- OK, but device was not recognized as part of config
+	#        9 -- ERROR with telldusd
+
+	local COMPONENT="$1"
+	local EXPECTEDSTATUS="$2"
+	local DEVICENUM=''
+	getDeviceNumber $COMPONENT
+	debugPrint "$COMPONENT has been found with device number $DEVICENUM"
+
+	if [ -z $DEVICENUM ]; then
+		debugPrint "Device not recognized, skipping"
+		return 2
+	fi
+
+	local STATUS=$( awk /$COMPONENT/'{print $NF}' "$TMPDIR"/FVE.statuses | tr '[:upper:]' '[:lower:]' )
+	if [ -z "$STATUS" ]; then
+		verbPrint "Error in getting real status, skipping"
+		return 9
+	fi
+	debugPrint "$COMPONENT [$DEVICENUM] = should be: $EXPECTEDSTATUS, is $STATUS"
+	if [ "$STATUS" = "$EXPECTEDSTATUS" ]; then
+		verbPrint "OK, nothing to change"
+		return 1
+	else
+		ERRMSG=$(tdtool --${EXPECTEDSTATUS,,} $DEVICENUM $VERBOUT )
+		if [ "$?" != "0" ]; then
+			echo "Problem with tdtool. Failed with message:"
+			echo "\"$ERRMSG\""
+			return 9
+		else
+			return 0
+		fi
+	fi
+}
+
+function opt() {
+	#usage opt $COMPONENT $EXPECTEDSTATUS
+	local COMPONENT=$1
+	local EXPECTEDSTATUS=${2,,}
+	
+	debugPrint "$COMPONENT: should be $EXPECTEDSTATUS"
+	if [ "$EXPECTEDSTATUS" = "on" -o  "$EXPECTEDSTATUS" = "off" ]; then
+		debugPrint "Turning $EXPECTEDSTATUS"
+
+		realStatus $COMPONENT $EXPECTEDSTATUS
+		local STATUS=$? 
+		if [ $STATUS = 0 -o "$FORCE" = "Y" ] ; then
+			FVEgenPage --update --device $COMPONENT $EXPECTEDSTATUS
+		fi
+	else
+		echo "Unknown parametr for function opt(): $@"
+	fi
 }
 
 function mainSetLoop() {
 	for i in `seq 0 $DEVICESTOTALNUM`; do
-		echo ${DEVICENAME[$i]}: ${DEVICESTATUS[$i]}
+		opt ${DEVICENAME[$i]} ${DEVICESTATUS[$i]}
 	done
 	return 0
 }
 
 function mainGetLoop() {
+	if [ ! -e "$TMPDIR"/FVE.statuses ]; then
+		getTDstatuses
+	fi
+	if [ $(grep "$DEVICENAMEGET" "$TMPDIR"/FVE.statuses | wc -l) -lt 1 ]; then
+		verbPrint "Not albe to get status for device $DEVICENAME"
+		exit 99
+	elif [ $(grep "$DEVICENAMEGET" "$TMPDIR"/FVE.statuses | wc -l) -gt 1 ]; then
+		verbPrint "Not albe to get unique status for device $DEVICENAME"
+		exit 99
+	fi
+	echo $( awk /$DEVICENAMEGET/'{print $NF}' "$TMPDIR"/FVE.statuses | tr '[:upper:]' '[:lower:]' )
 	return 0
 }
 
@@ -66,13 +136,13 @@ while [ $# -gt 0 ]; do
 				echo "Not enough params passed for --device $2"
 				exit 2
 			fi
-			if [ "$3" != 'on' -a "$3" != 'off' ] && [ "$3" != 'ON' -a "$3" != 'OFF' ] ; then
+			if [ "${3,,}" != 'on' -a "${3,,}" != 'off' -a "${3,,}" != 'notd' ] ; then
 				echo "3rd parametr may be only 'on/ON' or 'off/OFF'. Passed '$3' for device $2"
 				exit 3
 			fi
 			((++DEVICESTOTALNUM)) 
 			DEVICENAME[$DEVICESTOTALNUM]="$2"
-			DEVICESTATUS[$DEVICESTOTALNUM]=${3,,}
+			DEVICESTATUS[$DEVICESTOTALNUM]="${3,,}"
 			TYPE="SET"
 			shift 3
 			;;
@@ -81,15 +151,17 @@ while [ $# -gt 0 ]; do
 				echo "Not passed device parametr --getstatus"
 				exit 2
 			fi
-			DEVICENAME="$2"
+			DEVICENAMEGET="$2"
 			TYPE="GET"
 			shift 2
 			;;
-		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
-		--init) getStatusses; exit 0;;
+		--init) initFVEonOff; exit 0;;
 		--destroy) uninitStatuses ;exit 0;;
+		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
 	esac
 done
+
+
 
 if [ "$TYPE" = "SET" ]; then
 	mainSetLoop
