Add option to use /etc/FVErc not only ~/.FVErc

diff --git a/FVEoptRunV2 b/FVEoptRunV2
--- a/FVEoptRunV2
+++ b/FVEoptRunV2
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-source ~/.FVErc
+if [ -e ~/.FVErc ]; then 
+	source ~/.FVErc
+elif [ -e /etc/FVErc ]; then
+	source /etc/FVErc
+else
+	echo "FVErc not found!"
+	exit 99
+fi
+
 source "$FVEBINDIR"/FVEcomFncs
 
 OPTCFGFILE=$OPTCFGFILE
