FVEread: changed parcing params to while-do-done loop

diff --git a/FVEread b/FVEread
--- a/FVEread
+++ b/FVEread
@@ -165,28 +165,16 @@ VERBPARM=''
 VERBOUT=''
 VERB=''
 
-if [ "$#" = 1 ]; then
-	if [ "$1" = '-h' -o "$1" = "--help" ]; then
-		printHelp
-		exit
-	elif [ "$1" = "--stdout" ]; then
-		export STDOUT="YES"
-	elif [ "$1" = "--daemon" -o "$1" = "-d" ]; then
-		export DAEMON=1
-	elif [ "$1" = "-v" ]; then 
-		VERB=Y
-		VERBOUT=''
-		VERBPARM='-v'
-		shift
-	else
-		echo "Non supported parametr $1"
-		exit 1
-	fi
-elif [ "$#" -gt 1 ]; then
-	echo "Too much options"
-	printHelp
-	exit
-fi
+
+while [ $# -gt 0 ]; do
+	case $1 in
+		-h|--help) printHelp; exit; shift;;
+		-d|--daemon) DAEMON=1; shift;;
+		--stdout) STDOUT="YES" ; shift;;
+		-v|--verbose) VERB=Y; VERBOUT='';VERBPARM="-v" ; shift;;
+		*)  echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
+	esac
+done
 
 if [ $DAEMON ]; then
 	while true; do
